import { ReactNode } from 'react';
declare type OTPInputProps = {
    numOfInputs: number;
    placeHolder?: string;
    fieldSeperator?: ReactNode;
    filedClassName?: string;
    fieldWidth?: string;
    fieldHeight?: string;
    containerClassName?: string;
    autoFocus?: boolean;
    disabled?: boolean;
    isError?: boolean;
    isTypeNumber?: boolean;
    errorStyle?: Object;
    inpuStyle?: Object;
    inputFocusStyle?: Object;
    onChange: (otp: string) => void;
};
declare const OTPInput: (otpInputProps: OTPInputProps) => JSX.Element;
export default OTPInput;
